// src/app/layout.tsx (server component)

import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import ClientProviders from "./AuthProviderClient";

export const metadata: Metadata = {
  title: "Desco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ClientProviders>
          {children}
          <Toaster richColors />
        </ClientProviders>
      </body>
    </html>
  );
}
