// src/app/layout.tsx  (server component)

import type { Metadata } from "next";
import "./globals.css";
import ClientProviders from "./AuthProviderClient";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Desco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
         <Toaster richColors />
        <ClientProviders>{children}</ClientProviders>
        <Toaster />
      </body>
    </html>
  );
}
